# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-04 12:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='DEFAULT', max_length=128)),
                ('message', models.TextField(default='')),
                ('date', models.DateTimeField(verbose_name='eventDate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='DEFAULT', max_length=128, unique=True)),
                ('value', models.CharField(default='XXXX', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=128)),
                ('label', models.CharField(default='DEFAULT', max_length=128)),
                ('postalAdress', models.TextField(default='')),
                ('street', models.TextField(default='DEFAULT', max_length=128)),
                ('city', models.CharField(default='DEFAULT', max_length=128)),
                ('pays', models.CharField(default='DEFAULT', max_length=128)),
                ('lat', models.FloatField(blank=True, default=float("nan"), null=True)),
                ('lon', models.FloatField(blank=True, default=float("nan"), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitDate', models.DateTimeField()),
                ('name', models.CharField(default='DEFAULT', max_length=128, unique=True)),
                ('searchPattern', models.CharField(default='DEFAULT', max_length=256, unique=True)),
                ('metersArround', models.IntegerField(default=10000)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_of_request', to='whowlong.Place')),
                ('places', models.ManyToManyField(related_name='requests', to='whowlong.Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=128, unique=True)),
                ('type', models.CharField(default='CAR', max_length=128)),
                ('fromPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromPlace_of_Trajet', to='whowlong.Place')),
                ('toPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toPlace_of_Trajet', to='whowlong.Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrajetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trajetDate', models.DateTimeField()),
                ('distanceKm', models.FloatField(default=0.0)),
                ('dureeMinute', models.IntegerField(default=0)),
                ('trajetDateHeure', models.IntegerField(default=0)),
                ('trajetDateMinute', models.IntegerField(default=0)),
                ('computer', models.CharField(default='WAZE', max_length=128)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whowlong.Request')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whowlong.Trajet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
