# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whowlong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(blank=True, default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_of_request', to='whowlong.Place'),
        ),
        migrations.AlterField(
            model_name='request',
            name='submitDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
