# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-10 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whowlong', '0005_auto_20180907_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajetdata',
            name='user',
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(blank=True, default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='trajetdata',
            name='trajetDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
