# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-10 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whowlong', '0008_auto_20180910_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(blank=True, default=float("nan"), null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='searchPattern',
            field=models.CharField(default='DEFAULT', max_length=256),
        ),
    ]
